# Build stage
FROM node:20-alpine as build
WORKDIR /app
ARG VITE_TURSO_DATABASE_URL
ARG VITE_TURSO_AUTH_TOKEN
ARG VITE_TABLET_SETUP_PIN
ARG VITE_BOOTSTRAP_ADMIN_PIN
ARG VITE_DEFAULT_MANAGER_PIN
ARG VITE_DEFAULT_OPERATOR_PIN
ENV VITE_TURSO_DATABASE_URL=$VITE_TURSO_DATABASE_URL
ENV VITE_TURSO_AUTH_TOKEN=$VITE_TURSO_AUTH_TOKEN
ENV VITE_TABLET_SETUP_PIN=$VITE_TABLET_SETUP_PIN
ENV VITE_BOOTSTRAP_ADMIN_PIN=$VITE_BOOTSTRAP_ADMIN_PIN
ENV VITE_DEFAULT_MANAGER_PIN=$VITE_DEFAULT_MANAGER_PIN
ENV VITE_DEFAULT_OPERATOR_PIN=$VITE_DEFAULT_OPERATOR_PIN
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Production stage
FROM nginx:stable-alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
