# Build stage
FROM node:20-alpine as build
WORKDIR /app
ARG VITE_TURSO_DATABASE_URL
ARG VITE_TURSO_AUTH_TOKEN
ARG VITE_TABLET_SETUP_PIN
ARG VITE_BOOTSTRAP_ADMIN_PIN
ARG VITE_DEFAULT_MANAGER_PIN
ARG VITE_DEFAULT_OPERATOR_PIN
ARG VITE_OS_EMPRESA_ID
ARG VITE_OS_TENANT_SLUG
ARG VITE_OS_SYSTEM_USER_ID
ARG VITE_OS_ALLOWED_ORIGINS
ARG VITE_APP_VERSION
ARG VITE_APP_COMMIT
ENV VITE_TURSO_DATABASE_URL=$VITE_TURSO_DATABASE_URL
ENV VITE_TURSO_AUTH_TOKEN=$VITE_TURSO_AUTH_TOKEN
ENV VITE_TABLET_SETUP_PIN=$VITE_TABLET_SETUP_PIN
ENV VITE_BOOTSTRAP_ADMIN_PIN=$VITE_BOOTSTRAP_ADMIN_PIN
ENV VITE_DEFAULT_MANAGER_PIN=$VITE_DEFAULT_MANAGER_PIN
ENV VITE_DEFAULT_OPERATOR_PIN=$VITE_DEFAULT_OPERATOR_PIN
ENV VITE_OS_EMPRESA_ID=$VITE_OS_EMPRESA_ID
ENV VITE_OS_TENANT_SLUG=$VITE_OS_TENANT_SLUG
ENV VITE_OS_SYSTEM_USER_ID=$VITE_OS_SYSTEM_USER_ID
ENV VITE_OS_ALLOWED_ORIGINS=$VITE_OS_ALLOWED_ORIGINS
ENV VITE_APP_VERSION=$VITE_APP_VERSION
ENV VITE_APP_COMMIT=$VITE_APP_COMMIT
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM node:20-alpine
WORKDIR /app
COPY --from=build /app/dist ./dist
COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/package*.json ./
COPY server ./server
EXPOSE 80
CMD ["node", "server/bff.mjs"]
