export const createRouteHandlers = (services) => ({
  'GET /api/app/init': async (_body, context) => services.getAppSnapshotWithRetry({
    includeCatalog: true,
    includeAuditLimit: 50,
    view: context.url.searchParams.get('view') || 'pdv',
    session: context.session,
    operationAccessAllowed: context.operationAccessAllowed,
  }),
  'POST /api/app/sync': async (body, context) => services.getAppSnapshotWithRetry({
    includeCatalog: Boolean(body.includeCatalog),
    includeAuditLimit: 0,
    view: body.view || 'pdv',
    session: context.session,
    operationAccessAllowed: context.operationAccessAllowed,
  }),
  'POST /api/auth/login': async (body, context) => services.login(body, context),
  'POST /api/pdv-terminal/challenge': async (body) => services.issuePdvTerminalChallenge(body),
  'POST /api/pdv-terminal/authorize': async (body, context) => services.authorizePdvTerminal(body, context),
  'POST /api/tablet/setup-login': async (body, context) => services.validateTabletSetupPin(body, context),
  'POST /api/table-access-token': async (body, context) => services.createTableAccessToken(body, context.session),
  'POST /api/qr/resolve': async (body) => services.resolvePhysicalQrFlow(body),
  'GET /api/checklist-alerts': async () => services.getChecklistAlertsFromOs(),
  'POST /api/audit-logs/list': async (body) => ({
    auditLogs: await services.getAuditLogs({
      limit: Number(body.limit || 100),
      startDate: String(body.startDate || ''),
      endDate: String(body.endDate || ''),
      author: String(body.author || ''),
      action: String(body.action || ''),
    }),
  }),
  'POST /api/orders/send-to-kitchen': async (body, context) => services.sendToKitchen(body, context.session),
  'POST /api/delivery/quote': async (body) => services.getDeliveryQuote(body),
  'POST /api/delivery/postal-code': async (body) => ({ postalCode: await services.lookupDeliveryPostalCode(body) }),
  'POST /api/delivery/geocode': async (body) => ({ geocode: await services.geocodeDeliveryAddress(body?.customer || body) }),
  'POST /api/delivery/checkout': async (body) => services.createDeliveryCheckout(body),
  'POST /api/delivery/checkout/mock': async (body) => services.createDeliveryCheckout(body),
  'POST /api/delivery/webhooks/pagbank': async (body, context) => services.handlePagBankDeliveryWebhook(body, context),
  'POST /api/webhooks/pagbank': async (body, context) => services.handlePagBankDeliveryWebhook(body, context),
  'POST /api/delivery/customer/register': async (body, context) => services.createDeliveryCustomerAccount(body, context),
  'POST /api/delivery/customer/login': async (body) => services.loginDeliveryCustomer(body),
  'POST /api/delivery/customer/forgot-password': async (body, context) => services.requestDeliveryPasswordReset(body, context),
  'POST /api/delivery/customer/reset-password': async (body, context) => services.resetDeliveryCustomerPassword(body, context),
  'POST /api/delivery/customer/verify-code': async (body, context) => services.verifyDeliveryCustomerCode(body, context),
  'POST /api/customer-tabs/open': async (body) => services.openCustomerTab(body),
  'POST /api/customer-tabs/recover': async (body) => services.recoverCustomerTab(body),
  'POST /api/customer-tabs/payment-link': async (body, context) => services.createCustomerTabPaymentLink(body, context.session),
  'GET /api/customer-tabs/lookup': async (_body, context) => services.lookupCustomerTabs({ query: context.url.searchParams.get('q') || '' }),
  'POST /api/customer-tabs/finalize': async (body, context) => services.finalizeCustomerTab(body, context.session),
  'GET /api/delivery/customer/session': async (_body, context) => services.getDeliveryCustomerSession({ token: context.req?.headers['x-beco-delivery-session'] || '' }),
  'GET /api/delivery/customer/orders': async (_body, context) => services.listDeliveryCustomerOrders({ token: context.req?.headers['x-beco-delivery-session'] || '' }),
  'GET /api/delivery/order': async (_body, context) => services.getDeliveryOrder({
    orderId: context.url.searchParams.get('orderId') || '',
    session: context.session,
    customerSessionToken: context.req?.headers['x-beco-delivery-session'] || '',
    trackingToken: context.req?.headers['x-beco-delivery-tracking'] || '',
  }),
  'GET /api/delivery/order-detail': async (_body, context) => services.getDeliveryOrder({
    orderId: context.url.searchParams.get('orderId') || '',
    includeEvents: true,
    session: context.session,
  }),
  'GET /api/delivery/config': async () => services.getDeliveryPublicConfig(),
  'GET /api/delivery/pagbank/public-key': async () => services.getPagBankPublicKey(),
  'GET /api/delivery/orders': async (_body, context) => services.listDeliveryOrders({ limit: context.url.searchParams.get('limit') || 50 }),
  'POST /api/orders/status': async (body) => services.updateOrderStatus(body),
  'POST /api/order-items/delete': async (body, context) => services.deleteOrderItem(body, context.session),
  'POST /api/table-payments': async (body, context) => services.createTablePayment(body, context.session),
  'POST /api/table-payments/cancel': async (body, context) => services.cancelTablePayment(body, context.session),
  'GET /api/coupons/list': async () => services.listCoupons(),
  'POST /api/coupons/create': async (body, context) => services.createCoupon(body, context.session),
  'POST /api/coupons/validate': async (body, context) => services.validateCoupon(body, context.session),
  'POST /api/bills/close': async (body, context) => services.closeBillWithInventorySync(body, context.session),
  'POST /api/counter-sales/close': async (body, context) => services.closeCounterSaleWithInventorySync(body, context.session),
  'POST /api/catalog/category': async (body) => services.upsertCategory(body),
  'POST /api/catalog/category/delete': async (body) => services.deleteCategory(body),
  'POST /api/catalog/category/visibility': async (body) => services.toggleCategoryVisibility(body),
  'POST /api/catalog/product': async (body, context) => services.upsertProduct(body, context.session),
  'POST /api/catalog/product/cmv': async (body, context) => services.ensureCmvForMenuProduct(body, context.session),
  'POST /api/catalog/product/delete': async (body, context) => services.deleteProduct(body, context.session),
  'POST /api/catalog/product/visibility': async (body) => services.toggleProductVisibility(body),
  'POST /api/catalog/product/delivery-visibility': async (body) => services.toggleProductDeliveryVisibility(body),
  'POST /api/catalog/products/reorder': async (body, context) => services.reorderCatalogProducts(body, context.session),
  'POST /api/catalog/modifier-group': async (body) => services.saveModifierGroup(body),
  'POST /api/catalog/modifier-group/delete': async (body) => services.deleteModifierGroup(body),
  'POST /api/catalog/modifier-group/link': async (body) => services.linkModifierGroup(body),
  'POST /api/settings': async (body, context) => services.saveSettings(body, context.session),
  'POST /api/settings/qr-mode': async (body, context) => services.saveQrMode(body, context.session),
  'GET /api/pdv-lock/status': async () => services.getPdvLockState(),
  'POST /api/pdv-lock': async (body, context) => services.setPdvLockState(body, context.session),
  'GET /api/os-lock/status': async () => services.getOsLockState(),
  'POST /api/os-lock': async (body, context) => services.setOsLockState(body, context.session),
  'POST /api/qrcodes/regenerate': async (body, context) => services.regenerateTableQr(body, context.session),
  'POST /api/audit-logs': async (body) => services.addAuditLog(body),
  'POST /api/service-requests': async (body) => services.createServiceRequest(body),
  'POST /api/service-requests/resolve': async (body) => services.resolveServiceRequest(body),
  'POST /api/service-requests/clear': async (body) => services.clearServiceRequest(body),
  'POST /api/tables/request-bill': async (body) => services.requestBill(body),
  'POST /api/tables/status': async (body, context) => services.updateTableStatus(body, context.session),
  'POST /api/tables/open': async (body, context) => services.openTable(body, context.session),
  'POST /api/tables/transfer': async (body, context) => services.transferTable(body, context.session),
  'POST /api/tables/join': async (body, context) => services.joinTables(body, context.session),
  'GET /api/cash/status': async () => ({ cashState: await services.getCashState() }),
  'POST /api/cash/open': async (body, context) => services.openCash(body, context.session),
  'POST /api/cash/close': async (body, context) => services.closeCash(body, context.session),
  'POST /api/shifts/open': async (body) => services.openShift(body),
  'POST /api/shifts/close': async (body) => services.closeShift(body),
  'GET /api/closed-bills': async (_body, context) => ({
    closedBills: await services.getClosedBills(Number(context.url.searchParams.get('limit') || 5000), {
      from: context.url.searchParams.get('from') || '',
      to: context.url.searchParams.get('to') || '',
      extended: true,
    }),
  }),
  'POST /api/sellers': async (body, context) => services.addSeller(body, context.session),
  'POST /api/sellers/update': async (body, context) => services.updateSeller(body, context.session),
  'POST /api/sellers/pin': async (body) => services.updateSellerPin(body),
  'POST /api/sellers/delete': async (body) => services.deleteSeller(body),
  'POST /api/sellers/status': async (body) => services.updateSellerStatus(body),
  'GET /api/sellers/candidates': async () => ({ candidates: await services.listSellerCandidates() }),
  'POST /api/sellers/activate-os-user': async (body) => services.activateOsUserAsSeller(body),
  'POST /api/sellers/create-os-user': async (body) => services.createOsUserAsSeller(body),
  'POST /api/inventory/sync-beverages': async () => services.syncBeveragesFromInventory(),
  'POST /api/inventory/sync-open-orders': async () => services.syncOpenOrdersInventory(),
  'POST /api/inventory/reconcile-pending': async (body) => services.reconcilePendingInventoryEvents({
    limit: Number(body.limit || 10),
    includeAttention: Boolean(body.includeAttention),
  }),
});
