package com.becoartes.lio;

import android.app.*;
import android.os.*;
import android.content.*;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.net.Uri;
import android.text.*;
import android.text.InputType;
import android.text.style.ForegroundColorSpan;
import android.view.*;
import android.widget.*;
import org.json.*;
import java.util.*;
import java.net.URLEncoder;

/** Native Android UI. No WebView and no card data handled by Becoartes. */
public final class MainActivity extends Activity {
    private static final int BG=0xff0b0a10,CARD=0xff1b1920,CARD_2=0xff24212b,PURPLE=0xff8b4df6,PURPLE_DARK=0xff241735,WHITE=0xfff9f7ff,MUTED=0xff8f8a9b,GREEN=0xff00d39f,YELLOW=0xffffd21e,AMBER_BG=0xff4b2a05,AMBER_BORDER=0xffa86d00,BORDER=0xff34313b,ROSE=0xffff365f;
    private SecureStore store;private Api api;private LinearLayout root,content;private TextView notice;
    private boolean busy=false,onlyActive=false;private String page="",tableId="",name="",terminal="",category="Todas";
    private JSONObject quote;private JSONArray products=new JSONArray();private final Map<String,JSONObject> cart=new LinkedHashMap<>();
    private final Handler handler=new Handler();private long stoppedAt=0;
    private final Runnable poll=()->{if(!busy&&page.equals("tables"))loadTables();};
    private final Map<String,String> demoStorage=new HashMap<>();
    private String saved(String key){return api!=null&&api.demo!=null?demoStorage.getOrDefault(key,""):store.get(key);}
    private void save(String key,String value){if(api.demo!=null)demoStorage.put(key,value);else store.put(key,value);}
    private JSONObject obj(Object... values){JSONObject j=new JSONObject();try{for(int i=0;i<values.length;i+=2)j.put((String)values[i],values[i+1]);}catch(Exception e){throw new IllegalStateException(e);}return j;}
    private String brl(long cents){return java.text.NumberFormat.getCurrencyInstance(new Locale("pt","BR")).format(cents/100.0);}
    private int dp(int value){return (int)(getResources().getDisplayMetrics().density*value+.5f);}
    private GradientDrawable bg(int color){return panel(color,color,14);}
    private GradientDrawable panel(int color,int stroke,int radius){GradientDrawable d=new GradientDrawable();d.setColor(color);d.setCornerRadius(dp(radius));if(stroke!=color)d.setStroke(dp(1),stroke);return d;}
    private Typeface black(){return Typeface.create("sans-serif-black",Typeface.BOLD);}
    private Typeface medium(){return Typeface.create("sans-serif-medium",Typeface.NORMAL);}
    private Space space(LinearLayout parent,int height){Space s=new Space(this);parent.addView(s,new LinearLayout.LayoutParams(1,dp(height)));return s;}
    private TextView upper(LinearLayout parent,String text,int size,int color){TextView v=label(parent,text,size,color);v.setTypeface(black());v.setLetterSpacing(.16f);v.setAllCaps(true);return v;}
    private TextView action(LinearLayout parent,String text,boolean selected,Runnable run){TextView v=new TextView(this);v.setGravity(Gravity.CENTER);v.setText(text);v.setTextSize(10);v.setTypeface(black());v.setLetterSpacing(.12f);v.setTextColor(selected?WHITE:MUTED);v.setBackground(panel(selected?PURPLE:CARD,selected?PURPLE:BORDER,13));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,dp(44),1);lp.setMargins(dp(3),0,dp(3),0);parent.addView(v,lp);v.setOnClickListener(x->{if(!busy)run.run();});return v;}

    @Override public void onCreate(Bundle state){super.onCreate(state);getWindow().setStatusBarColor(BG);getWindow().setNavigationBarColor(BG);
        try{store=new SecureStore(this);api=new Api(store);handleCallback(getIntent());if(saved("device").isEmpty())activation();else login();}
        catch(Exception e){new AlertDialog.Builder(this).setTitle("Becoartes").setMessage(e.getMessage()).setPositiveButton("Fechar",(d,w)->finish()).show();}}
    @Override protected void onNewIntent(Intent intent){super.onNewIntent(intent);setIntent(intent);handleCallback(intent);if(!saved("session").isEmpty()&&!saved("pendingPayment").isEmpty())recovery();}
    @Override protected void onStop(){super.onStop();stoppedAt=System.currentTimeMillis();handler.removeCallbacks(poll);}
    @Override protected void onResume(){super.onResume();if(api==null)return;if(stoppedAt>0&&System.currentTimeMillis()-stoppedAt>5*60000&&saved("pendingPayment").isEmpty()&&!saved("session").isEmpty()){save("session","");login();}else if(page.equals("tables"))handler.postDelayed(poll,1000);}
    @Override public void onBackPressed(){if(busy)return;if(!saved("pendingPayment").isEmpty()){recovery();return;}if(!saved("pendingOrder").isEmpty()){orderRecovery();return;}if(page.equals("catalog")){if(cart.isEmpty())loadTable();else new AlertDialog.Builder(this).setMessage("Descartar a seleção ainda não enviada?").setNegativeButton("Continuar",null).setPositiveButton("Descartar",(d,w)->{cart.clear();loadTable();}).show();}else if(page.equals("table")||page.equals("payment"))loadTables();else if(api.demo!=null)leaveDemo();else login();}
    private void screen(String title,String subtitle){handler.removeCallbacks(poll);root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(16),dp(12),dp(16),dp(12));root.setBackgroundColor(BG);setContentView(root);
        if(api.demo!=null)label(root,"DEMONSTRAÇÃO • NÃO MOVIMENTA O PDV",11,YELLOW);
        if(!title.isEmpty()){TextView heading=label(root,title,28,WHITE);heading.setTypeface(black());heading.setLetterSpacing(-.025f);}if(!subtitle.isEmpty()){TextView sub=label(root,subtitle,12,MUTED);sub.setTypeface(medium());}
        ScrollView scroll=new ScrollView(this);scroll.setFillViewport(true);scroll.setScrollbarFadingEnabled(false);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));
        content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(0,dp(12),0,dp(8));scroll.addView(content);
        notice=label(root,"",13,YELLOW);notice.setAccessibilityLiveRegion(View.ACCESSIBILITY_LIVE_REGION_POLITE);
    }
    private TextView label(LinearLayout parent,String text,int size,int color){TextView v=new TextView(this);v.setText(text);v.setTextSize(size);v.setTextColor(color);v.setTypeface(medium());v.setPadding(0,dp(5),0,dp(5));parent.addView(v);return v;}
    private Button button(LinearLayout parent,String text,int color,Runnable action){Button b=new Button(this);b.setText(text);b.setTextColor(color==YELLOW||color==GREEN?BG:WHITE);b.setAllCaps(false);b.setTypeface(black());b.setTextSize(14);b.setMinHeight(dp(52));b.setBackground(panel(color,color==CARD?BORDER:color,16));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,dp(7),0,dp(3));parent.addView(b,lp);b.setOnClickListener(v->{if(!busy)action.run();});return b;}
 private EditText input(LinearLayout parent,String hint,boolean numeric){EditText e=new EditText(this);e.setSingleLine(true);e.setTextColor(WHITE);e.setHintTextColor(MUTED);e.setTypeface(medium());e.setTextSize(18);e.setPadding(dp(14),dp(12),dp(14),dp(12));e.setBackground(panel(CARD,BORDER,16));e.setHint(hint);e.setInputType(numeric?InputType.TYPE_CLASS_NUMBER:InputType.TYPE_CLASS_TEXT);if(Build.VERSION.SDK_INT>=26)e.setImportantForAutofill(View.IMPORTANT_FOR_AUTOFILL_NO);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,dp(56));lp.setMargins(0,dp(8),0,dp(8));parent.addView(e,lp);return e;}
    private void error(String message,int status){busy=false;notice.setText(message);if(status==410&&!saved("pendingPayment").isEmpty()){save("pendingPayment","");stopService(new Intent(this,PaymentService.class));loadTables();}else if(status==401&&!page.equals("login")&&!page.equals("activation")){save("session","");login();notice.setText(message);}else if(page.equals("orderRecovery")&&(status==400||status==403||status==409)){button(content,"Voltar à conta para corrigir",CARD,()->{save("pendingOrder","");cart.clear();loadTable();});}}
    private void call(String path,JSONObject data,Api.Done done){if(busy)return;busy=true;notice.setText("Aguarde…");api.call(path,data,r->{busy=false;notice.setText("");done.accept(r);},this::error);}
    private void activation(){page="activation";screen("Becoartes PDV","LIO ON • ativação pelo administrador");label(content,"No computador, acesse PDV → Maquininhas. Gere um código para este terminal e digite abaixo.",16,WHITE);
        EditText code=input(content,"Código de ativação",false);button(content,"Ativar maquininha",PURPLE,()->call("activate",obj("code",code.getText().toString()),r->{save("device",r.getString("deviceToken"));save("terminal",r.getString("terminal"));login();}));
        button(content,"Ver demonstração offline",CARD,()->{try{api.demo=new Demo();demoStorage.clear();login();}catch(Exception e){error(e.getMessage(),0);}});
        label(content,"Suporte: adm.becoartes@gmail.com\n(11) 97471-7013",13,MUTED);
    }
    private void leaveDemo(){busy=false;api.demo=null;demoStorage.clear();cart.clear();if(saved("device").isEmpty())activation();else login();}
    private void login(){page="login";screen("","");content.setGravity(Gravity.CENTER_HORIZONTAL);
        space(content,20);
        FrameLayout badge=new FrameLayout(this);badge.setBackground(panel(PURPLE_DARK,PURPLE_DARK,28));LinearLayout.LayoutParams badgeLp=new LinearLayout.LayoutParams(dp(80),dp(80));badgeLp.gravity=Gravity.CENTER_HORIZONTAL;content.addView(badge,badgeLp);
        ImageView people=new ImageView(this);people.setImageResource(R.drawable.ic_launcher);people.setPadding(dp(13),dp(13),dp(13),dp(13));badge.addView(people,new FrameLayout.LayoutParams(-1,-1));
        space(content,22);
        SpannableString title=new SpannableString("IDENTIFICAÇÃO PDV");title.setSpan(new ForegroundColorSpan(PURPLE),13,title.length(),Spanned.SPAN_EXCLUSIVE_EXCLUSIVE);TextView heading=label(content,title.toString(),28,WHITE);heading.setText(title);heading.setTypeface(black());heading.setGravity(Gravity.CENTER);heading.setLetterSpacing(-.035f);
        TextView subtitle=upper(content,api.demo!=null?"DEMONSTRAÇÃO • USE O PIN 1234":"INSIRA SEU PIN DE ACESSO PARA ENTRAR NO TERMINAL OPERACIONAL",10,MUTED);subtitle.setGravity(Gravity.CENTER);subtitle.setMaxWidth(dp(340));subtitle.setLineSpacing(dp(3),1f);
        space(content,34);
        EditText pin=input(content,"••••",true);pin.setInputType(InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_VARIATION_PASSWORD);pin.setFilters(new InputFilter[]{new InputFilter.LengthFilter(4)});pin.setGravity(Gravity.CENTER);pin.setTextSize(30);pin.setLetterSpacing(.32f);pin.setBackground(panel(CARD_2,BORDER,22));LinearLayout.LayoutParams pinLp=(LinearLayout.LayoutParams)pin.getLayoutParams();pinLp.height=dp(84);pinLp.setMargins(0,0,0,dp(14));pin.setLayoutParams(pinLp);
        Button enter=button(content,"ENTRAR",PURPLE,()->{String code=pin.getText().toString();if(!code.matches("[0-9]{4}")){notice.setText("Digite os quatro dígitos do seu PIN.");return;}call("login",obj("pin",code),r->{save("session",r.getString("session"));name=r.getJSONObject("seller").getString("name");terminal=r.getString("terminal");pin.setText("");
            if(!saved("pendingPayment").isEmpty())recovery();else if(!saved("pendingOrder").isEmpty())orderRecovery();else restorePending();});});
        enter.setTextSize(15);LinearLayout.LayoutParams enterLp=(LinearLayout.LayoutParams)enter.getLayoutParams();enterLp.height=dp(64);enter.setLayoutParams(enterLp);
        if(api.demo!=null){Button leave=button(content,"SAIR DA DEMONSTRAÇÃO",CARD,this::leaveDemo);leave.setTextSize(11);}
        TextView helper=label(content,"O PIN identifica quem lançou os pedidos e recebeu os pagamentos.",12,MUTED);helper.setGravity(Gravity.CENTER);helper.setPadding(dp(20),dp(14),dp(20),0);
    }
    private void restorePending(){call("payments/pending",null,r->{JSONArray list=r.getJSONArray("payments");if(list.length()==0){loadTables();return;}JSONObject p=list.getJSONObject(0);save("pendingPayment",obj("id",p.getString("id"),"nonce",UUID.randomUUID().toString(),"prepare",obj("tableId",p.getString("table_id"),"method",p.getString("method"))).toString());recovery();});}
    private void loadTables(){if(busy)return;page="tables";screen("","");
        LinearLayout brand=new LinearLayout(this);brand.setGravity(Gravity.CENTER_VERTICAL);content.addView(brand,new LinearLayout.LayoutParams(-1,-2));
        ImageView mark=new ImageView(this);mark.setImageResource(R.drawable.ic_launcher);mark.setPadding(0,dp(6),dp(8),dp(6));brand.addView(mark,new LinearLayout.LayoutParams(dp(30),dp(40)));
        LinearLayout identity=new LinearLayout(this);identity.setOrientation(LinearLayout.VERTICAL);brand.addView(identity,new LinearLayout.LayoutParams(0,-2,1));upper(identity,"MAPA DE MESAS",11,MUTED);TextView operator=label(identity,name+(terminal.isEmpty()?"":" • LIO "+terminal),12,WHITE);operator.setPadding(0,0,0,0);
        TextView exit=new TextView(this);exit.setText("SAIR");exit.setGravity(Gravity.CENTER);exit.setTextColor(MUTED);exit.setTextSize(10);exit.setTypeface(black());exit.setBackground(panel(CARD,BORDER,12));LinearLayout.LayoutParams exitLp=new LinearLayout.LayoutParams(dp(58),dp(40));brand.addView(exit,exitLp);exit.setOnClickListener(v->{if(!busy)call("logout",obj(),r->{save("session","");cart.clear();login();});});
        space(content,18);
        LinearLayout filters=new LinearLayout(this);filters.setPadding(dp(3),dp(3),dp(3),dp(3));filters.setBackground(panel(CARD,BORDER,16));content.addView(filters,new LinearLayout.LayoutParams(-1,dp(50)));
        action(filters,"TODAS AS MESAS",!onlyActive,()->{onlyActive=false;loadTables();});action(filters,"MESAS ABERTAS",onlyActive,()->{onlyActive=true;loadTables();});
        space(content,14);
        LinearLayout grid=new LinearLayout(this);grid.setOrientation(LinearLayout.VERTICAL);content.addView(grid,new LinearLayout.LayoutParams(-1,-2));
        call("tables",null,r->{JSONArray list=r.getJSONArray("tables");List<JSONObject> shown=new ArrayList<>();for(int j=0;j<list.length();j++){JSONObject t=list.getJSONObject(j);boolean active=!t.optString("status").equals("available");if(!onlyActive||active)shown.add(t);}
            for(int j=0;j<shown.size();j+=2){LinearLayout row=new LinearLayout(this);grid.addView(row,new LinearLayout.LayoutParams(-1,-2));LinearLayout.LayoutParams left=new LinearLayout.LayoutParams(0,dp(122),1);left.setMargins(dp(3),dp(4),dp(3),dp(4));row.addView(tableCard(shown.get(j)),left);if(j+1<shown.size()){LinearLayout.LayoutParams right=new LinearLayout.LayoutParams(0,dp(122),1);right.setMargins(dp(3),dp(4),dp(3),dp(4));row.addView(tableCard(shown.get(j+1)),right);}else{Space filler=new Space(this);LinearLayout.LayoutParams blank=new LinearLayout.LayoutParams(0,dp(122),1);blank.setMargins(dp(3),dp(4),dp(3),dp(4));row.addView(filler,blank);}}
            if(shown.isEmpty()){TextView empty=label(grid,"Nenhuma mesa aberta agora.",16,MUTED);empty.setGravity(Gravity.CENTER);empty.setPadding(0,dp(60),0,dp(60));}handler.postDelayed(poll,15000);});
    }
    private View tableCard(JSONObject t){boolean active=!t.optString("status").equals("available");boolean pending=t.optBoolean("paymentPending");int fill=active?AMBER_BG:CARD;int stroke=active?AMBER_BORDER:BORDER;int color=active?YELLOW:MUTED;if(pending){fill=0xff41121f;stroke=ROSE;color=0xffff6b88;}
        LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setPadding(dp(15),dp(13),dp(15),dp(12));card.setBackground(panel(fill,stroke,18));card.setClickable(true);card.setFocusable(true);
        LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER_VERTICAL);card.addView(top,new LinearLayout.LayoutParams(-1,0,1));TextView number=label(top,String.valueOf(t.optInt("number")),26,color);number.setTypeface(black());number.setPadding(0,0,0,0);Space push=new Space(this);top.addView(push,new LinearLayout.LayoutParams(0,1,1));if(active){ImageView people=new ImageView(this);people.setImageResource(android.R.drawable.ic_menu_myplaces);people.setColorFilter(color);top.addView(people,new LinearLayout.LayoutParams(dp(20),dp(20)));}
        String bottom=active?brl(t.optLong("subtotalCents")):"INICIAR";if(pending)bottom="EM PAGAMENTO";TextView value=upper(card,bottom,active?16:10,color);value.setLetterSpacing(active?-.01f:.14f);value.setPadding(0,0,0,0);
        if(t.optBoolean("individual")||pending){card.setAlpha(.72f);card.setEnabled(false);}else card.setOnClickListener(v->{if(!busy){tableId=t.optString("id");loadTable();}});return card;}
    private void loadTable(){page="table";screen("","");
        LinearLayout nav=new LinearLayout(this);nav.setGravity(Gravity.CENTER_VERTICAL);content.addView(nav,new LinearLayout.LayoutParams(-1,dp(48)));TextView back=new TextView(this);back.setText("‹");back.setTextSize(38);back.setGravity(Gravity.CENTER);back.setTextColor(WHITE);back.setBackground(panel(CARD,BORDER,14));nav.addView(back,new LinearLayout.LayoutParams(dp(48),dp(44)));back.setOnClickListener(v->{if(!busy)loadTables();});LinearLayout navText=new LinearLayout(this);navText.setOrientation(LinearLayout.VERTICAL);navText.setPadding(dp(12),0,0,0);nav.addView(navText,new LinearLayout.LayoutParams(0,-2,1));upper(navText,"CONTA DA MESA",10,MUTED);TextView user=label(navText,name,12,WHITE);user.setPadding(0,0,0,0);
        space(content,12);
        call("quote?tableId="+Uri.encode(tableId),null,r->{quote=r;JSONObject t=r.getJSONObject("table");SpannableString mesa=new SpannableString("MESA "+t.optInt("number"));mesa.setSpan(new ForegroundColorSpan(PURPLE),5,mesa.length(),Spanned.SPAN_EXCLUSIVE_EXCLUSIVE);TextView title=label(content,mesa.toString(),34,WHITE);title.setText(mesa);title.setTypeface(black());title.setLetterSpacing(-.035f);upper(content,"PEDIDOS ATIVOS",10,MUTED);JSONArray lines=t.getJSONArray("orders");
            if(lines.length()==0){LinearLayout empty=new LinearLayout(this);empty.setPadding(dp(16),dp(22),dp(16),dp(22));empty.setBackground(panel(CARD,BORDER,18));TextView emptyText=label(empty,"Nenhum item lançado. Adicione produtos para abrir o atendimento.",14,MUTED);emptyText.setGravity(Gravity.CENTER);content.addView(empty,new LinearLayout.LayoutParams(-1,-2));}
            for(int j=0;j<lines.length();j++){JSONObject i=lines.getJSONObject(j);long unit=Math.round(i.optDouble("price")*100);JSONArray mods=i.optJSONArray("selectedModifiers");String suffix="";if(mods!=null)for(int k=0;k<mods.length();k++){JSONObject m=mods.getJSONObject(k);unit+=Math.round(m.optDouble("price")*100);suffix+="\n+ "+m.optString("name");}
                LinearLayout item=new LinearLayout(this);item.setOrientation(LinearLayout.VERTICAL);item.setPadding(dp(14),dp(12),dp(14),dp(12));item.setBackground(panel(CARD,BORDER,16));LinearLayout.LayoutParams itemLp=new LinearLayout.LayoutParams(-1,-2);itemLp.setMargins(0,dp(4),0,dp(4));content.addView(item,itemLp);LinearLayout line=new LinearLayout(this);line.setGravity(Gravity.TOP);item.addView(line,new LinearLayout.LayoutParams(-1,-2));TextView itemName=label(line,i.optInt("quantity")+"× "+i.optString("name"),16,WHITE);itemName.setTypeface(black());line.addView(new Space(this),new LinearLayout.LayoutParams(0,1,1));TextView itemValue=label(line,brl(unit*i.optInt("quantity")),15,WHITE);itemValue.setTypeface(black());if(!suffix.isEmpty()){TextView extras=label(item,suffix.trim(),11,MUTED);extras.setPadding(0,dp(4),0,0);}}
            space(content,12);LinearLayout totals=new LinearLayout(this);totals.setOrientation(LinearLayout.VERTICAL);totals.setPadding(dp(16),dp(13),dp(16),dp(13));totals.setBackground(panel(CARD,BORDER,18));content.addView(totals,new LinearLayout.LayoutParams(-1,-2));moneyLine(totals,"SUBTOTAL",brl(r.optLong("subtotalCents")),MUTED,13);moneyLine(totals,"TAXA DE SERVIÇO",brl(r.optLong("serviceFeeCents")),MUTED,13);space(totals,5);moneyLine(totals,"TOTAL",brl(r.optLong("subtotalCents")+r.optLong("serviceFeeCents")),WHITE,21);moneyLine(totals,"PAGO",brl(r.optLong("paidCents")),GREEN,14);moneyLine(totals,"FALTA",brl(r.optLong("balanceCents")),YELLOW,20);
            space(content,10);button(content,"ADICIONAR ITENS",PURPLE,this::catalog);button(content,"IMPRIMIR CONTA",CARD,this::printBill);
            if(r.getLong("balanceCents")>0)button(content,"PAGAMENTO",GREEN,this::payment);else if(lines.length()>0)button(content,"FINALIZAR E LIBERAR MESA",GREEN,()->finishTable());});
    }
    private void moneyLine(LinearLayout parent,String caption,String value,int color,int size){LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);parent.addView(row,new LinearLayout.LayoutParams(-1,-2));TextView key=upper(row,caption,10,MUTED);row.addView(new Space(this),new LinearLayout.LayoutParams(0,1,1));TextView amount=label(row,value,size,color);amount.setTypeface(black());}
    private void summary(LinearLayout parent,JSONObject q){label(parent,"Subtotal   "+brl(q.optLong("subtotalCents")),15,MUTED);label(parent,"Taxa de serviço   "+brl(q.optLong("serviceFeeCents")),15,MUTED);
        label(parent,"Total   "+brl(q.optLong("subtotalCents")+q.optLong("serviceFeeCents")),22,WHITE);label(parent,"Pago   "+brl(q.optLong("paidCents")),15,GREEN);label(parent,"Falta   "+brl(q.optLong("balanceCents")),22,YELLOW);}
    private void catalog(){page="catalog";screen("Adicionar itens","Mesa "+quote.optJSONObject("table").optInt("number"));button(root,"← Conta",CARD,()->onBackPressed());
        call("catalog",null,r->{products=r.getJSONArray("products");category="Todas";drawCatalog();});}
    private String normalize(String s){return java.text.Normalizer.normalize(s,java.text.Normalizer.Form.NFD).replaceAll("\\p{M}","").toLowerCase(Locale.ROOT);}
    private void drawCatalog(){screen("Adicionar itens","Selecione vários produtos e envie juntos");page="catalog";
        EditText search=input(content,"Buscar produto em todas as categorias",false);Spinner categories=new Spinner(this);List<String> names=new ArrayList<>();names.add("Todas");for(int i=0;i<products.length();i++){String c=products.optJSONObject(i).optString("categoryName");if(!names.contains(c))names.add(c);}
        categories.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,names));content.addView(categories);
        LinearLayout results=new LinearLayout(this);results.setOrientation(1);content.addView(results);Button submit=button(root,"Adicionar seleção",PURPLE,this::submitOrder);
        Runnable draw=()->{results.removeAllViews();String query=normalize(search.getText().toString());int count=0;for(int n=0;n<products.length();n++){JSONObject p=products.optJSONObject(n);String id=p.optString("id");if(!query.isEmpty()&&!normalize(p.optString("name")).contains(query))continue;if(query.isEmpty()&&!category.equals("Todas")&&!category.equals(p.optString("categoryName")))continue;count++;
            LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);row.setPadding(dp(8),dp(8),dp(8),dp(8));row.setBackground(bg(CARD));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,dp(4),0,dp(4));results.addView(row,lp);
            ImageView photo=new ImageView(this);photo.setImageResource(android.R.drawable.ic_menu_gallery);photo.setScaleType(ImageView.ScaleType.CENTER_CROP);photo.setContentDescription(p.optString("name"));row.addView(photo,new LinearLayout.LayoutParams(dp(48),dp(48)));Images.load(p.optString("image"),photo);
            CheckBox select=new CheckBox(this);select.setTextColor(WHITE);select.setText(p.optString("name")+"\n"+brl(Math.round(p.optDouble("price")*100))+(cart.containsKey(id)?" • "+cart.get(id).optInt("quantity")+" un.":""));select.setChecked(cart.containsKey(id));row.addView(select,new LinearLayout.LayoutParams(0,-2,1));
            select.setOnClickListener(v->{if(busy)return;if(!select.isChecked()){cart.remove(id);submit.setText("Adicionar seleção ("+cart.size()+")");}else configureProduct(p,()->{select.setChecked(cart.containsKey(id));select.setText(p.optString("name")+"\n"+brl(Math.round(p.optDouble("price")*100))+(cart.containsKey(id)?" • "+cart.get(id).optInt("quantity")+" un.":""));submit.setText("Adicionar seleção ("+cart.size()+")");});});
            select.setOnLongClickListener(v->{configureProduct(p,()->drawCatalog());return true;});}
            if(count==0)label(results,"Nenhum produto encontrado.",16,MUTED);submit.setText("Adicionar seleção ("+cart.size()+")");};
        categories.setOnItemSelectedListener(new android.widget.AdapterView.OnItemSelectedListener(){public void onNothingSelected(android.widget.AdapterView<?> p){}public void onItemSelected(android.widget.AdapterView<?> p,View v,int pos,long id){category=names.get(pos);draw.run();}});
        search.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int c,int f){}public void onTextChanged(CharSequence s,int a,int b,int c){draw.run();}public void afterTextChanged(Editable e){}});draw.run();button(root,"← Voltar à conta",CARD,()->onBackPressed());
    }
    private void configureProduct(JSONObject p,Runnable changed){LinearLayout box=new LinearLayout(this);box.setOrientation(1);box.setPadding(dp(20),dp(12),dp(20),dp(12));EditText qty=input(box,"Quantidade",true);qty.setText("1");EditText notes=input(box,"Observação (opcional)",false);notes.setFilters(new InputFilter[]{new InputFilter.LengthFilter(300)});
        Map<String,CheckBox> choices=new LinkedHashMap<>();JSONArray groups=p.optJSONArray("modifierGroups");
        if(groups!=null)for(int g=0;g<groups.length();g++){JSONObject group=groups.optJSONObject(g);label(box,group.optString("name")+" • "+group.optInt("minChoices")+" a "+group.optInt("maxChoices",1)+" opções",16,WHITE);JSONArray modifiers=group.optJSONArray("modifiers");if(modifiers==null)continue;for(int m=0;m<modifiers.length();m++){JSONObject option=modifiers.optJSONObject(m);if(!option.optString("status").equals("active")||option.optBoolean("inheritedUnavailable"))continue;CheckBox b=new CheckBox(this);b.setTextColor(WHITE);b.setText(option.optString("name")+"  +"+brl(Math.round(option.optDouble("price")*100)));box.addView(b);choices.put(option.optString("id"),b);}}
        ScrollView scroll=new ScrollView(this);scroll.addView(box);AlertDialog dialog=new AlertDialog.Builder(this).setTitle(p.optString("name")).setView(scroll).setNegativeButton("Cancelar",(d,w)->changed.run()).setPositiveButton("Selecionar",null).create();dialog.setOnCancelListener(d->changed.run());dialog.setOnShowListener(d->dialog.getButton(-1).setOnClickListener(v->{try{
            int amount=Integer.parseInt(qty.getText().toString());if(amount<1||amount>99)throw new Exception("Quantidade de 1 a 99.");JSONArray ids=new JSONArray();for(String id:choices.keySet())if(choices.get(id).isChecked())ids.put(id);
            if(groups!=null)for(int g=0;g<groups.length();g++){JSONObject group=groups.getJSONObject(g);int selected=0;JSONArray mods=group.getJSONArray("modifiers");for(int m=0;m<mods.length();m++){CheckBox b=choices.get(mods.getJSONObject(m).getString("id"));if(b!=null&&b.isChecked())selected++;}if(selected<Math.max(group.optInt("minChoices"),group.optBoolean("isRequired")?1:0)||selected>group.optInt("maxChoices",1))throw new Exception("Confira "+group.getString("name"));}
            cart.put(p.getString("id"),obj("productId",p.getString("id"),"quantity",amount,"modifierIds",ids,"notes",notes.getText().toString()));dialog.dismiss();changed.run();
        }catch(Exception e){Toast.makeText(this,e.getMessage(),Toast.LENGTH_LONG).show();}}));dialog.show();}
    private void submitOrder(){if(cart.isEmpty()){notice.setText("Selecione pelo menos um produto.");return;}JSONArray lines=new JSONArray();for(JSONObject item:cart.values())lines.put(item);JSONObject request=obj("requestId",UUID.randomUUID().toString(),"tableId",tableId,"items",lines);save("pendingOrder",request.toString());orderRecovery();sendOrder();}
    private void orderRecovery(){page="orderRecovery";screen("Envio do pedido","Não envie uma segunda vez com outro aparelho.");label(content,"O pedido está salvo neste aparelho. Se a conexão caiu, consultar/envia novamente a MESMA solicitação, sem duplicar os itens.",17,WHITE);button(content,"Concluir envio do pedido",PURPLE,this::sendOrder);}
    private void sendOrder(){try{JSONObject data=new JSONObject(saved("pendingOrder"));tableId=data.getString("tableId");call("orders",data,r->{save("pendingOrder","");cart.clear();loadTable();notice.setText("Pedido enviado à cozinha/bar conforme o catálogo.");});}catch(Exception e){error(e.getMessage(),0);}}
    private void payment(){page="payment";screen("","");
        LinearLayout nav=new LinearLayout(this);nav.setGravity(Gravity.CENTER_VERTICAL);content.addView(nav,new LinearLayout.LayoutParams(-1,dp(48)));TextView back=new TextView(this);back.setText("‹");back.setTextSize(38);back.setGravity(Gravity.CENTER);back.setTextColor(WHITE);back.setBackground(panel(CARD,BORDER,14));nav.addView(back,new LinearLayout.LayoutParams(dp(48),dp(44)));back.setOnClickListener(v->{if(!busy)loadTable();});LinearLayout navText=new LinearLayout(this);navText.setOrientation(LinearLayout.VERTICAL);navText.setPadding(dp(12),0,0,0);nav.addView(navText,new LinearLayout.LayoutParams(0,-2,1));upper(navText,"PAGAMENTO",10,MUTED);TextView table=label(navText,"Mesa "+quote.optJSONObject("table").optInt("number"),18,WHITE);table.setTypeface(black());table.setPadding(0,0,0,0);
        space(content,14);LinearLayout totals=new LinearLayout(this);totals.setOrientation(LinearLayout.VERTICAL);totals.setPadding(dp(16),dp(13),dp(16),dp(13));totals.setBackground(panel(CARD,BORDER,18));content.addView(totals,new LinearLayout.LayoutParams(-1,-2));moneyLine(totals,"TOTAL DA CONTA",brl(quote.optLong("subtotalCents")+quote.optLong("serviceFeeCents")),WHITE,20);moneyLine(totals,"PAGO",brl(quote.optLong("paidCents")),GREEN,14);moneyLine(totals,"FALTA RECEBER",brl(quote.optLong("balanceCents")),YELLOW,20);
        space(content,14);upper(content,"FORMA DE PAGAMENTO",10,MUTED);String[] labels={"CRÉDITO","DÉBITO","PIX • QR CIELO","DINHEIRO"};String[] codes={"credit","debit","pix","cash"};int[] selected={-1};List<TextView> cards=new ArrayList<>();LinearLayout methods=new LinearLayout(this);methods.setOrientation(LinearLayout.VERTICAL);content.addView(methods,new LinearLayout.LayoutParams(-1,-2));
        for(int start=0;start<labels.length;start+=2){LinearLayout row=new LinearLayout(this);methods.addView(row,new LinearLayout.LayoutParams(-1,-2));for(int offset=0;offset<2;offset++){int index=start+offset;TextView choice=new TextView(this);choice.setText(labels[index]);choice.setGravity(Gravity.CENTER);choice.setTextSize(11);choice.setTypeface(black());choice.setTextColor(MUTED);choice.setBackground(panel(CARD,BORDER,16));LinearLayout.LayoutParams choiceLp=new LinearLayout.LayoutParams(0,dp(62),1);choiceLp.setMargins(dp(3),dp(4),dp(3),dp(4));row.addView(choice,choiceLp);cards.add(choice);choice.setOnClickListener(v->{selected[0]=index;for(int c=0;c<cards.size();c++){TextView option=cards.get(c);boolean on=c==selected[0];option.setTextColor(on?WHITE:MUTED);option.setBackground(panel(on?PURPLE:CARD,on?PURPLE:BORDER,16));}});}}
        space(content,10);upper(content,"VALOR RECEBIDO",10,MUTED);EditText amount=input(content,"0,00",true);amount.setText(String.format(new Locale("pt","BR"),"%.2f",quote.optLong("balanceCents")/100.0));amount.selectAll();amount.setTextSize(25);amount.setTypeface(black());
        amount.addTextChangedListener(new TextWatcher(){boolean edit;public void beforeTextChanged(CharSequence s,int a,int c,int f){}public void onTextChanged(CharSequence s,int a,int b,int c){}public void afterTextChanged(Editable e){if(edit)return;edit=true;String digits=e.toString().replaceAll("[^0-9]","");if(digits.length()>9)digits=digits.substring(0,9);long value=digits.isEmpty()?0:Long.parseLong(digits);amount.setText(String.format(new Locale("pt","BR"),"%.2f",value/100.0));amount.setSelection(amount.length());edit=false;}});
        button(content,"RECEBER PAGAMENTO",GREEN,()->{int methodIndex=selected[0];if(methodIndex<0||methodIndex>3){notice.setText("Escolha a forma de pagamento.");return;}long received;try{received=Long.parseLong(amount.getText().toString().replaceAll("[^0-9]",""));}catch(Exception e){received=0;}long balance=quote.optLong("balanceCents");String method=codes[methodIndex];if(received<=0){notice.setText("Informe um valor maior que zero.");return;}if(received>balance&&!method.equals("cash")){notice.setText("Você informou "+brl(received)+"; a conta tem "+brl(balance)+" a receber. Troco somente em dinheiro.");return;}
            JSONObject data=obj("requestId",UUID.randomUUID().toString(),"tableId",tableId,"fingerprint",quote.optString("fingerprint"),"method",method,"amount",Math.min(received,balance),"received",received);
            if(method.equals("cash")){long change=Math.max(0,received-balance);new AlertDialog.Builder(this).setTitle("Confirmar dinheiro recebido").setMessage("Recebido: "+brl(received)+"\nTroco: "+brl(change)+"\nConfirme somente com o dinheiro em mãos.").setNegativeButton("Voltar",null).setPositiveButton("Recebi",(d,w)->prepare(data)).show();}else prepare(data);});
    }
    private void prepare(JSONObject data){save("pendingPayment",obj("prepare",data,"nonce",UUID.randomUUID().toString()).toString());recovery();preparePending(true);}
    private void preparePending(boolean first){try{JSONObject pending=new JSONObject(saved("pendingPayment"));JSONObject data=pending.getJSONObject("prepare");call("payments/prepare",data,r->{pending.put("id",r.getString("id"));save("pendingPayment",pending.toString());
            if(data.getString("method").equals("cash")||api.demo!=null){settle();return;}
            if(!first||r.optBoolean("recovery")||!r.has("request")){recovery();notice.setText("Consulte a operação. Não há autorização para iniciar outra cobrança.");return;}
            JSONObject request=r.getJSONObject("request");String callback=new Uri.Builder().scheme("becoarteslio").authority("payment").appendQueryParameter("nonce",pending.getString("nonce")).build().toString();
            Intent intent=new Intent(Intent.ACTION_VIEW,new Uri.Builder().scheme("lio").authority("payment").appendQueryParameter("request",android.util.Base64.encodeToString(request.toString().getBytes("UTF-8"),android.util.Base64.NO_WRAP)).appendQueryParameter("urlCallback",callback).build());
            if(intent.resolveActivity(getPackageManager())==null){notice.setText("Serviço Cielo não instalado neste aparelho. Operação permanece pendente para conferência.");return;}
            Intent service=new Intent(this,PaymentService.class);if(Build.VERSION.SDK_INT>=26)startForegroundService(service);else startService(service);
            startActivity(intent);
        });}catch(Exception e){error(e.getMessage(),0);}}
    private void recovery(){page="recovery";screen("Conferir pagamento","Não faça outra cobrança desta conta.");label(content,"Se o cartão/Pix já foi aprovado, consulte abaixo para registrar no PDV. A consulta não cobra novamente.",18,WHITE);button(content,"Consultar e registrar pagamento",GREEN,()->{try{JSONObject p=new JSONObject(saved("pendingPayment"));if(p.has("id"))settle();else preparePending(false);}catch(Exception e){error(e.getMessage(),0);}});label(content,"Se não houver confirmação, peça ajuda ao caixa. Não apague os dados do app.",14,YELLOW);}
    private void settle(){try{JSONObject p=new JSONObject(saved("pendingPayment"));JSONObject prepare=p.getJSONObject("prepare");tableId=prepare.getString("tableId");call("payments/settle",obj("id",p.getString("id"),"orderId",p.optString("orderId")),r->{long change=r.optLong("changeCents");save("pendingPayment","");stopService(new Intent(this,PaymentService.class));loadTable();new AlertDialog.Builder(this).setTitle("Pagamento registrado").setMessage(change>0?"Troco: "+brl(change):"Pagamento sincronizado com o PDV.").setPositiveButton("OK",null).show();});}catch(Exception e){error(e.getMessage(),0);}}
    private void handleCallback(Intent intent){Uri uri=intent==null?null:intent.getData();if(uri==null||!"becoarteslio".equals(uri.getScheme()))return;try{
        if("payment".equals(uri.getHost())&&!saved("pendingPayment").isEmpty()){JSONObject p=new JSONObject(saved("pendingPayment"));if(!p.getString("nonce").equals(uri.getQueryParameter("nonce")))return;String encoded=uri.getQueryParameter("response");if(encoded==null||encoded.length()>200000)return;JSONObject response=new JSONObject(new String(android.util.Base64.decode(encoded,android.util.Base64.DEFAULT),"UTF-8"));if(response.has("id"))p.put("orderId",response.getString("id"));save("pendingPayment",p.toString());}
        else if("print".equals(uri.getHost())&&saved("printNonce").equals(uri.getQueryParameter("nonce"))&&!saved("printNonce").isEmpty()){save("printNonce","");String encoded=uri.getQueryParameter("response");if(encoded!=null){JSONObject r=new JSONObject(new String(android.util.Base64.decode(encoded,android.util.Base64.DEFAULT),"UTF-8"));Toast.makeText(this,r.optInt("code",-1)==0?"Conta impressa.":"Impressão não concluída. Confira papel e impressora.",Toast.LENGTH_LONG).show();}}
    }catch(Exception ignored){/* Untrusted callback. Reconciliation always queries server/Cielo. */}}
    private void printBill(){call("quote?tableId="+Uri.encode(tableId),null,r->{quote=r;String text=r.getString("receipt");if(api.demo!=null){new AlertDialog.Builder(this).setTitle("Prévia da conta • DEMO").setMessage(text).setPositiveButton("OK",null).show();return;}
        String nonce=UUID.randomUUID().toString();save("printNonce",nonce);JSONObject request=obj("operation","PRINT_TEXT","styles",new JSONArray().put(obj()),"value",new JSONArray().put(text));
        Intent intent=new Intent(Intent.ACTION_VIEW,new Uri.Builder().scheme("lio").authority("print").appendQueryParameter("request",android.util.Base64.encodeToString(request.toString().getBytes("UTF-8"),android.util.Base64.NO_WRAP)).appendQueryParameter("urlCallback","becoarteslio://print?nonce="+nonce).build());
        if(intent.resolveActivity(getPackageManager())==null){notice.setText("Impressora Cielo indisponível neste aparelho.");return;}startActivity(intent);});}
    private void finishTable(){call("finish",obj("tableId",tableId,"fingerprint",quote.optString("fingerprint")),r->{loadTables();notice.setText("Conta finalizada. Mesa liberada no PDV.");});}
}
